#!/bin/bash

git add *
git status

echo "Continue? y/n"
read INPUT
while [ $INPUT != "n" ] && [ $INPUT != "y" ] 
do
	echo "type y or n"
	read INPUT
done
if [ $INPUT == "n" ]; then
	echo "Stop executing the script"
	exit 0
fi
echo "Write a comment"
read COMMIT
git commit -m "$COMMIT"
echo "Push? y/n"
read INPUT
while [ $INPUT != "n" ] && [ $INPUT != "y" ] 
do
	echo "type y or n"
	read INPUT
done
if [ $INPUT == "y" ]; then
	git push
fi
